// <auto-generated />
namespace crmBI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class march : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(march));
        
        string IMigrationMetadata.Id
        {
            get { return "202103311341483_march"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
